In [1]:
import tensorflow as tf
from tensorflow import keras

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [4]:
def hamilton(p,q,time_step):
    #p1, q1 = 
    #H = p**2 + q**2 # spring hamiltonian (linear oscillator)
    pdot, qdot = -2*q , 2*p
    p2, q2 = p+(pdot*time_step) , q+(qdot*time_step)  
    return p2,q2

In [6]:
hamilton(1,1,0.1)[0]

0.8

In [20]:
p,q=np.float16(1),np.float16(1)
trajectory=np.array([])
ps=np.array([])
qs=np.array([])
time=0.1
while time<=10:
    p,q = hamilton(p,q,time)[0],hamilton(p,q,time)[1]
    #trajectory=np.append(trajectory,[p,q])
    ps=np.append(ps,p*10)
    qs=np.append(qs,q*10)
    time+=0.1

In [25]:
ps;

In [13]:
cordinat=np.array([3,4])
h=hamilton(cordinat,3)[0]
h2=hamilton(cordinat,3)[1]
print(h.ndim,h2.ndim)
hamilton(cordinat,3)

1 1


(array([-21]), array([22]))

In [30]:
type(cordinat[1])

numpy.int64

In [23]:
?np.split

In [4]:
ll=np.array([])

In [15]:
ll=np.append(ll,hamilton(cordinat,2),axis=0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [10]:
ll

array([-21.,  22., -13.,  16.])

In [14]:
hamilton(cordinat,0.2)

(array([1.4]), array([5.2]))

In [6]:
trajectory

array([], dtype=float64)

In [10]:
def trainData():
        for i in range 

SyntaxError: unexpected EOF while parsing (<ipython-input-10-11318d631079>, line 2)

In [ ]:
def HNN():
    

In [5]:
myModel=keras.models.Sequential()
myModel.add(keras.layers.Flatten(input_shape=[2]))
myModel.add(keras.layers.Dense(200, activation="tanh"))
myModel.add(keras.layers.Dense(200, activation="tanh"))
myModel.add(keras.layers.Dense(2, activation="softmax"))

In [7]:
myModel.compile(loss="loss",
    optimizer="Adam",
    metrics=["accuracy"])

In [ ]:
trainedModel=model.fit(X_train, y_train, epochs=30,
                      validation_data=(X_valid, y_valid))

In [ ]:
def loss():
    
    

In [9]:
ll=np.arry([1,2,3])
ll.sum()

AttributeError: module 'numpy' has no attribute 'arry'